on:
  push:
    branches:
      - preview

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.*'  # Change this to the .NET version you're using

      - name: Read version from version.props
        working-directory: ExampleLibrary
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/preview" ]]; then
            version=$(grep -oP '<Version>\K[^<]+' common.props)
            echo "VERSION=$version-preview.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          else
            version=$(grep -oP '<Version>\K[^<]+' common.props)
            echo "VERSION=$version" >> $GITHUB_ENV
          fi

      - name: Build project
        working-directory: ExampleLibrary
        run: dotnet build ExampleLibrary.sln --configuration Release /p:Version=$VERSION /p:Platform="Any CPU"

      - name: Pack
        working-directory: ExampleLibrary
        run: dotnet pack ExampleLibrary.sln --configuration Release --output nupkgs /p:Version=$VERSION /p:Platform="Any CPU"

      - name: Publish NuGet packages
        working-directory: ExampleLibrary
        run: |
          for pkg in nupkgs/*.nupkg; do
            dotnet nuget push "$pkg" --source "${{ secrets.PREVIEW_NUGET_FEED_URL }}" --api-key "${{ secrets.PREVIEW_NUGET_API_KEY }}"
          done
